- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 72000 #20 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 72000 #20 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs # Corvax-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 512000 #??? hrs # Corvax-RoleTime
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom # Corvax-JobSupervisors
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: BoxFolderBlack
    pocket2: PenCentcom
